name:                Semirings
version:             0.1.0.0
github:              "montetzouma/Semirings"
license:             BSD3
author:              "George Illambas"
maintainer:          "gillambas@gmail.com"
copyright:           "2020 George Illambas"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Implementation of "Fun with Semirings" and solution to programming competition problems.
category:            Haskell,Optimisation,Competitive Programming
description:         Please see the README on GitHub at <https://github.com/montetzouma/Semirings#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- split

library:
  source-dirs: src

tests:
  Semirings-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Semirings
